# Generated by Django 4.0.8 on 2023-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_tab_pmb_quantum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmbl03wpca',
            name='commitment_check',
            field=models.CharField(default='N', max_length=1, verbose_name='Commitment Check'),
        ),
    ]
