# Generated by Django 4.0.8 on 2023-04-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_wbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMBL03Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmb_L03_schedule_code', models.CharField(max_length=55, unique=True, verbose_name='PMB L03 Schedule Code')),
                ('pmb_L03_schedule_title', models.CharField(blank=True, max_length=2000, null=True, verbose_name='PMB L03 Schedule Title')),
                ('early_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Early Start Date')),
                ('early_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Early Finish Date')),
                ('early_start_to_early_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='Early Start to Early Finish Duration')),
                ('late_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Late Start Date')),
                ('late_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Late Finish Date')),
                ('late_start_to_late_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='Late Start to Late Finish Duration')),
                ('critical_path_check', models.IntegerField(default=0, verbose_name='Critical Path Check')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='PMB Comments')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.discipline', verbose_name='Discipline Code')),
                ('pmb_L03_wp_exe_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.pmbl03wpexecutiontype', verbose_name='PMB L03 Work Package Execution Type Code')),
            ],
            options={
                'verbose_name_plural': 'PMB L03 Schedule',
                'db_table': 'pmb_L03_schedule',
                'ordering': ['pmb_L03_schedule_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PMBL04Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmb_L04_schedule_code', models.CharField(max_length=55, unique=True, verbose_name='PMB L04 Schedule Code')),
                ('pmb_L04_schedule_title', models.CharField(blank=True, max_length=2000, null=True, verbose_name='PMB L04 Schedule Title')),
                ('early_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Early Start Date')),
                ('early_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Early Finish Date')),
                ('early_start_to_early_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='Early Start to Early Finish Duration')),
                ('late_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Late Start Date')),
                ('late_finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Late Finish Date')),
                ('late_start_to_late_finish_duration', models.IntegerField(blank=True, null=True, verbose_name='Late Start to Late Finish Duration')),
                ('critical_path_check', models.IntegerField(default=0, verbose_name='Critical Path Check')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='CB Comments')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_wbs.discipline', verbose_name='Discipline Code')),
                ('pmb_L03_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_schedules.pmbl03schedule', verbose_name='PMB L03 Schedule ID')),
                ('pmb_L04_wp_exe_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.pmbl04wpexecutiontype', verbose_name='PMB L04 Work Package Execution Type Code')),
            ],
            options={
                'verbose_name_plural': 'PMB L04 Schedule',
                'db_table': 'pmb_L04_schedule',
                'ordering': ['pmb_L04_schedule_code'],
                'managed': True,
            },
        ),
    ]
