# Generated by Django 4.0.8 on 2023-04-19 17:43

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('z_tab_pmb_quantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmbL04WpActuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateTimeField(verbose_name='Calendar Date')),
                ('forecast_actual_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Forecasted Actuals Hours on Calendar Date')),
                ('forecast_actual_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3)),
                ('forecast_actual_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=18, null=True, verbose_name='Forecasted Actuals Costs on Calendar Date')),
                ('incurred_actual_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Incurred Actuals Hours on Calendar Date')),
                ('incurred_actual_costs_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'CA$')], default='CAD', editable=False, max_length=3)),
                ('incurred_actual_costs', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='CAD', max_digits=18, null=True, verbose_name='Incurred Actuals Costs on Calendar Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('pmb_L04_wp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_tab_pmb_quantum.pmbl04wp', verbose_name='PMB L04 WP ID')),
            ],
            options={
                'verbose_name_plural': 'PMB L04 WP Actuals',
                'db_table': 'pmb_L04_wp_actuals',
                'ordering': ['pmb_L04_wp', 'calendar_date'],
                'managed': True,
                'unique_together': {('pmb_L04_wp', 'calendar_date')},
            },
        ),
    ]
