# Generated by Django 4.0.8 on 2023-04-19 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('z_tab_pmb_quantum', '0001_initial'),
        ('f_contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_route_code', models.CharField(max_length=5, unique=True, verbose_name='Claim Type Code')),
                ('claim_route_title', models.CharField(max_length=55, unique=True, verbose_name='Claim Type Title')),
            ],
            options={
                'verbose_name_plural': 'Claims - Route',
                'db_table': 'claim_route',
                'ordering': ['claim_route_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type_code', models.CharField(max_length=5, unique=True, verbose_name='Claim Type Code')),
                ('claim_type_title', models.CharField(max_length=55, unique=True, verbose_name='Claim Type Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Claims - Types',
                'db_table': 'claim_type',
                'ordering': ['claim_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmbL03WpClaimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Claim Number')),
                ('claim_initiation_date', models.DateTimeField(verbose_name='Claim Initiation Date')),
                ('claim_title', models.CharField(max_length=55, unique=True, verbose_name='Claim Title')),
                ('claim_summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Claim Summary')),
                ('cbwp_hours_change_sought', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='PMB WP CA L04 Hours Change Sought')),
                ('cbwp_hours_change_approved', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='PMB WP CA L04 Hours Change Approved')),
                ('cbwp_costs_change_sought', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='PMB WP CA L04 Costs Change Sought')),
                ('cbwp_costs_change_approved', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='PMB WP CA L04 Costs Change Approved')),
                ('cbwp_daily_extension_sought', models.IntegerField(blank=True, null=True, verbose_name='PMB WP CA L04 Daily Extension Sought')),
                ('cbwp_daily_extension_approved', models.IntegerField(blank=True, null=True, verbose_name='PMB WP CA L04 Daily Extension Approved')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('claim_route', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_claims.claimroute', verbose_name='Claim Route ID')),
                ('claim_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_claims.claimtype', verbose_name='Claim Type ID')),
                ('pmb_L03_wp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_tab_pmb_quantum.pmbl03wp', verbose_name='PMB L03 WP ID')),
            ],
            options={
                'verbose_name_plural': 'PMB L03 WP Claims',
                'db_table': 'pmb_L03_wp_claim',
                'managed': True,
                'unique_together': {('pmb_L03_wp', 'claim_number')},
            },
        ),
        migrations.CreateModel(
            name='PmbL03WpClaimDetailContractClauseReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('contract_clause', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='f_contracts.contractclauses', verbose_name='Contract Clause ID')),
                ('pmb_L03_wp_claim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='m_claims.pmbl03wpclaimdetail', verbose_name='PMB L03 WP Claim Detail ID')),
            ],
            options={
                'verbose_name_plural': 'PMB L03 WP Claims With Contract Clauses',
                'db_table': 'pmb_L03_wp_claim_clause',
                'managed': True,
                'unique_together': {('pmb_L03_wp_claim', 'contract_clause')},
            },
        ),
    ]
