# Generated by Django 4.0.8 on 2023-04-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_code', models.CharField(max_length=15, unique=True, verbose_name='Commodity Code')),
                ('commodity_title', models.CharField(blank=True, max_length=155, null=True, unique=True, verbose_name='Commodity Title')),
            ],
            options={
                'verbose_name_plural': 'Commodities',
                'db_table': 'commodity',
                'ordering': ['commodity_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommodityCameose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_code_cameose', models.CharField(max_length=15, unique=True, verbose_name='Cameose Commodity Code')),
                ('commodity_title_cameose', models.CharField(blank=True, max_length=155, null=True, unique=True, verbose_name='Cameose Commodity Title')),
            ],
            options={
                'verbose_name_plural': 'Commodities - Cameose',
                'db_table': 'commodity_cameose',
                'ordering': ['commodity_code_cameose'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_type_code', models.CharField(max_length=5, unique=True, verbose_name='Commodity Type Code')),
                ('commodity_type_title', models.CharField(blank=True, max_length=155, null=True, unique=True, verbose_name='Commodity Type Title')),
            ],
            options={
                'verbose_name_plural': 'Commodity Types',
                'db_table': 'commodity_type',
                'ordering': ['commodity_type_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommodityTypeCameose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_type_code_cameose', models.CharField(max_length=5, unique=True, verbose_name='Cameose Commodity Type Code')),
                ('commodity_type_title_cameose', models.CharField(blank=True, max_length=155, null=True, unique=True, verbose_name='Cameose Commodity Type Title')),
            ],
            options={
                'verbose_name_plural': 'Commodity Types - Cameose',
                'db_table': 'commodity_type_cameose',
                'ordering': ['commodity_type_code_cameose'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommodityDetailCameose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_detail_code_cameose', models.CharField(max_length=15, unique=True, verbose_name='Cameose Commodity Detail Code')),
                ('commodity_detail_title_cameose', models.CharField(blank=True, max_length=155, null=True, unique=True, verbose_name='Cameose Commodity Detail Title')),
                ('commodity_cameose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commodities.commoditycameose', verbose_name='Cameose Commodity ID')),
            ],
            options={
                'verbose_name_plural': 'Commodity Details - Cameose',
                'db_table': 'commodity_detail_cameose',
                'ordering': ['commodity_detail_code_cameose'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommodityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_detail_code', models.CharField(max_length=15, unique=True, verbose_name='Commodity Detail Code')),
                ('commodity_detail_title', models.CharField(blank=True, max_length=155, null=True, unique=True, verbose_name='Commodity Detail Title')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commodities.commodity', verbose_name='Commodity ID')),
            ],
            options={
                'verbose_name_plural': 'Commodity Details',
                'db_table': 'commodity_detail',
                'ordering': ['commodity_detail_code'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='commoditycameose',
            name='commodity_type_cameose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commodities.commoditytypecameose', verbose_name='Cameose Commodity Type ID'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='commodity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commodities.commoditytype', verbose_name='Commodity Type ID'),
        ),
    ]
