# Generated by Django 4.0.8 on 2023-04-19 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=3, unique=True, verbose_name='Company Code')),
                ('company_title', models.CharField(max_length=55, unique=True, verbose_name='Company Title')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company E-mail')),
                ('business_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Business Phone')),
                ('fax_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Fax Number')),
                ('address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 2')),
                ('zip_postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='ZIP/Postal Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('web_page', models.URLField(blank=True, max_length=250, null=True, verbose_name='Wep Page')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
                'ordering': ['company_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_cat_code', models.CharField(max_length=1, unique=True, verbose_name='Company Category Code')),
                ('company_cat_title', models.CharField(max_length=55, unique=True, verbose_name='Company Category Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Company Categories',
                'db_table': 'company_category',
                'ordering': ['company_cat_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonnelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_cat_code', models.CharField(max_length=1, unique=True, verbose_name='Personnel Category Code')),
                ('personnel_cat_title', models.CharField(max_length=55, unique=True, verbose_name='Personnel Category Title')),
            ],
            options={
                'verbose_name_plural': 'Personnel Categories',
                'db_table': 'personnel_category',
                'ordering': ['personnel_cat_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_code', models.CharField(max_length=1, unique=True, verbose_name='Privilege Code')),
                ('privilege_title', models.CharField(max_length=55, unique=True, verbose_name='Privilege Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Privileges',
                'db_table': 'privilege',
                'ordering': ['privilege_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RaciMatrixDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raci_code', models.CharField(max_length=1, unique=True, verbose_name='RACI Code')),
                ('raci_title', models.CharField(max_length=15, unique=True, verbose_name='RACI Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'RACI Matrix Definition',
                'db_table': 'raci_matrix_definition',
                'ordering': ['raci_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StakeholderRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_role_code', models.CharField(max_length=5, unique=True, verbose_name='Stakeholder Role Code')),
                ('stakeholder_role_title', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='Stakeholder Role Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Stakeholder Roles',
                'db_table': 'stakeholder_role',
                'ordering': ['stakeholder_role_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=3, unique=True, verbose_name='Personnel Code')),
                ('personnel_title', models.CharField(max_length=55, verbose_name='Personnel Title')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('business_phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Business Phone')),
                ('home_phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Home Phone')),
                ('mobile_phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Mobile Phone')),
                ('address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 2')),
                ('zip_postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='ZIP/Postal Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_hr.company', verbose_name='Company ID')),
                ('personnel_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_hr.personnelcategory', verbose_name='Personnel Category ID')),
            ],
            options={
                'verbose_name_plural': 'Personnel',
                'db_table': 'personnel',
                'ordering': ['personnel_code'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_hr.companycategory', verbose_name='Company Category ID'),
        ),
    ]
