# Generated by Django 4.0.8 on 2023-04-19 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_commodities', '0001_initial'),
        ('b_wbs', '0001_initial'),
        ('g_measures', '0001_initial'),
        ('a_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhasesBenchmarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_phase_code', models.CharField(max_length=5, unique=True, verbose_name='Project Phase Code')),
                ('project_phase_title', models.CharField(blank=True, max_length=55, null=True, verbose_name='Project Phase Title')),
                ('project_phase_venue', models.CharField(blank=True, max_length=55, null=True, verbose_name='Project Phase Venue')),
                ('project_phase_start_dt', models.DateTimeField(blank=True, null=True, verbose_name='Project Phase Start Date')),
                ('project_phase_finish_dt', models.DateTimeField(blank=True, null=True, verbose_name='Project Phase Finish Date')),
                ('project_phase_comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Project Phase Comments')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'Project Phases for Benchmarking',
                'db_table': 'project_phase_benchmarking',
                'ordering': ['project_phase_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=5, unique=True, verbose_name='Project Code')),
                ('project_title', models.CharField(blank=True, max_length=55, null=True, verbose_name='Project Title')),
                ('client_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='Client Name')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Project Comments')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['project_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WBSLocationsForProjectPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs_location_code_project_phase', models.CharField(max_length=5, unique=True, verbose_name='WBS Location Code for Project Phase')),
                ('wbs_location_title_project_phase', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='WBS Location Title for Project Phase')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='WBS Location Comments')),
                ('project_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_benchmarking.projectphasesbenchmarking', verbose_name='Project Phase ID')),
            ],
            options={
                'verbose_name_plural': 'WBS Locations for Project Phases',
                'db_table': 'wbs_location_project_phases',
                'ordering': ['wbs_location_code_project_phase'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='projectphasesbenchmarking',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_benchmarking.projects', verbose_name='Project ID'),
        ),
        migrations.CreateModel(
            name='ProjectDataRepositoryCostItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdr_cost_item_code', models.CharField(max_length=5, verbose_name='PDR Cost Item Code')),
                ('pdr_cost_item_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='PDR Cost Item Title')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Quantity')),
                ('all_in_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='All-In Costs')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Unit Price')),
                ('geo_region', models.CharField(blank=True, max_length=55, null=True, verbose_name='Geographical Location')),
                ('capture_dt', models.DateTimeField(blank=True, null=True, verbose_name='Capture Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('commodity_cameose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commodities.commoditycameose', verbose_name='Commodity Deliverable ID')),
                ('discipline', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.discipline', verbose_name='Discipline ID')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_hr.company', verbose_name='Supplier ID')),
                ('uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_measures.uom', verbose_name='EBWP UOM ID')),
                ('wbs_location_project_phases', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_benchmarking.wbslocationsforprojectphases', verbose_name='WBS Location ID for Project Phases')),
            ],
            options={
                'verbose_name_plural': 'PDR Cost Items',
                'db_table': 'pdr_cost_item',
                'ordering': ['pdr_cost_item_code'],
                'managed': True,
                'unique_together': {('commodity_cameose', 'supplier', 'pdr_cost_item_code', 'capture_dt')},
            },
        ),
        migrations.CreateModel(
            name='CommodityWeightedUnitPriceAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wupa_code', models.CharField(max_length=5, unique=True, verbose_name='WUPA Code')),
                ('wupa_title', models.CharField(max_length=55, unique=True, verbose_name='WUPA Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('commodity_cameose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commodities.commoditycameose', verbose_name='Commodity ID')),
                ('uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_measures.uom', verbose_name='WUPA UOM ID')),
            ],
            options={
                'verbose_name_plural': 'Weighted Unit Price Averages',
                'db_table': 'wupa_commodity',
                'ordering': ['wupa_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommodityWeightedUnitPriceAverageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_contracts', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Contracts')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Quantity')),
                ('all_in_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='All-In Costs')),
                ('avg_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Avergare Bid Cost per UOM')),
                ('geo_region', models.CharField(blank=True, max_length=55, null=True, verbose_name='Geographical Location')),
                ('capture_dt', models.DateTimeField(blank=True, null=True, verbose_name='Capture Date')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('wupa_commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_benchmarking.commodityweightedunitpriceaverages', verbose_name='WUPA Commodity ID')),
            ],
            options={
                'verbose_name_plural': 'Weighted Unit Price Average Commodity Details',
                'db_table': 'wupa_commodity_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectDataRepositoryCostItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Item Item No')),
                ('item_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Item Item Title')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Quantity')),
                ('labour_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Labour Costs')),
                ('material_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Material Costs')),
                ('equipment_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Equipment Costs')),
                ('cmr_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Contingency and Management Reserve Costs')),
                ('ohp_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Overhead and Profit Costs')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('pdr_cost_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_benchmarking.projectdatarepositorycostitems', verbose_name='PDR Cost Item ID')),
                ('uom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_measures.uom', verbose_name='EBWP UOM ID')),
            ],
            options={
                'verbose_name_plural': 'PDR Cost Item Labour Details',
                'db_table': 'pdr_cost_item_details',
                'ordering': ['item_no'],
                'managed': True,
                'unique_together': {('pdr_cost_item', 'item_no')},
            },
        ),
    ]
